#!/usr/bin/python
# coding=utf-8

import sys, os


class Jungle:
    def __init__(self):
        self.root = os.path.split(os.path.realpath(__file__))[0]
        self.scriptRoot = os.path.join(self.root, 'script')
        self.baseScriptRoot = os.path.join(self.scriptRoot, 'base')
        self.pyToolRoot = os.path.join(self.scriptRoot, 'pytool')
        self.resourcesRoot = os.path.join(self.root, 'resources')
        self.projectTemplateRoot = os.path.join(self.resourcesRoot, 'project_template')
        self.configureRoot = os.path.join(self.resourcesRoot, 'configure')
        self.cmd_list = [
            ('-h, --help', '', self.__showHelp, '使用帮助'),
            ('install', '', self.__install, '安装'),
            ('maven, mvn', '<name> [path]', self.__newMavenProject, '\n\t创建maven项目，必须指定项目名称，不指定路径默认就是当前路径'),
            ('cmake', '<name> [path]', self.__newStandardCMakeProject, '创建标准CMake项目，自带gtest和glog'),
            ('cmakemod', '<name> [path]', self.__newCMakeModule, '创建CMake子模块'),
            ('cpp0', '<name> [path]', self.__newSimpleCMakeProject, '创建基础CMake项目'),
            ('new', '<kind> <name> [path]', self.__newFile, '\n\t创建文件, kind:c,cc,cpp,cclass,cheader,ctest,py'),
            ('vim', '', self.__configVim, 'vim配置'),
            ('idea', '', self.__configIDEA, 'idea配置'),
            ('tmux', '', self.__configTmux, 'tmux配置'),
            ('time', '', self.__timetool, 'time工具'),
        ]

    def __showHelp(self):
        title = '-' * 30 + ' Jungle ' + '-' * 30
        print title
        print '用法: jungle command [args]\n'
        for cmd in self.cmd_list:
            print cmd[0] + ' ' + cmd[1] + ': ' + cmd[3]
        print '-' * len(title)

    def __install(self):
        print '安装jungle...'
        os.system('sh %s' % (os.path.join(self.baseScriptRoot, 'install_jungle.sh')))
        print '安装完成，请执行source ~/.bashrc'

    def __newMavenProject(self, name, path='.'):
        print '创建maven工程...............'
        print '项目名称: %s' % (name)
        print '项目路径: %s' % (os.path.realpath(path))
        os.system('sh %s %s %s %s' % (os.path.join(self.baseScriptRoot, 'new_maven.sh'), os.path.join(self.projectTemplateRoot, 'SimpleMaven'), os.path.realpath(path), name))

    def __newSimpleCMakeProject(self, name, path='.'):
        print '创建Simple CMake工程...............'
        print '项目名称: %s' % (name)
        print '项目路径: %s' % (os.path.realpath(path))
        os.system('sh %s %s %s %s' % (os.path.join(self.baseScriptRoot, 'new_simple_cmake.sh'), os.path.join(self.projectTemplateRoot, 'SimpleCMake'), path, name))

    def __newStandardCMakeProject(self, name, path='.'):
        print '创建Standard CMake工程...............'
        print '项目名称: %s' % (name)
        print '项目路径: %s' % (os.path.realpath(path))
        os.system('sh %s %s %s %s' % (os.path.join(self.baseScriptRoot, 'new_standard_cmake.sh'), os.path.join(self.projectTemplateRoot, 'StandardCMake'), os.path.realpath(path), name))

    def __newCMakeModule(self, name, path='.'):
        print '创建CMake子模块...............'
        print '模块名称: %s' % (name)
        print '模块路径: %s' % (os.path.realpath(path))
        os.system('sh %s %s %s %s' % (os.path.join(self.baseScriptRoot, 'new_cmake_module.sh'), os.path.join(self.projectTemplateRoot, 'CMakeSubModule'), os.path.realpath(path), name))
        
    def __nameTransform(self, name):
        #if '_' not in name:
        #   return name
        return ''.join([x.title() for x in name.split('_')])

    def __newFile(self, kind, name, path='.'):
        if kind in ['cpp', 'cc', 'c', 'cheader', 'cclass', 'ctest']:
            print '创建%s文件...............' % kind
            if kind == 'ctest':
                print '文件名称: %s.cc' % (name)
                filename = os.path.join(path, name)
                f = open(filename + '.cc', 'w')
                f.write('#include "gtest/gtest.h"\n')
                f.write('\nTEST(%s, test) {\n\n}\n' % self.__nameTransform(name));
                f.close()
                return
            elif kind not in ['cheader', 'cclass']:
                print '文件名称: %s.h %s.%s' % (name, name, kind)
            elif kind == 'cheader':
                print '文件名称: %s.h' % (name)
            elif kind == 'cclass':
                print '文件名称: %s.h %s.cc' % (name, name)
            print '文件路径: %s' % (os.path.realpath(path))
            filename = os.path.join(path, name)
            f = open(filename + '.h', 'w')
            f.write('#ifndef __%s_H\n' % name.upper())
            f.write('#define __%s_H\n' % name.upper())
            if kind == 'cclass':
                name1 = self.__nameTransform(name)
                f.write('class %s {\n\tpublic:\n\t\t%s(){}\n\t\tvirtual ~%s(){}\n\n\tprivate:\n\n};\n\n' % (name1, name1, name1))
                pass
            f.write('#endif')
            f.close()
            if kind != 'cheader':
                kind = 'cc' if kind == 'cclass' else kind
                f = open(filename + ('.%s' % kind), 'w')
                f.write('#include "%s.h"\n\n' % name)
                f.close()
        elif kind == 'py':
            print '创建%s文件...............' % kind
            print '文件名: %s.py' % name
            filename = os.path.join(path, name)
            f = open(filename + '.py', 'w')
            f.write('#!/usr/bin/python\n#coding=utf-8\n\n\nif __name__ == \'__main__\':\n    pass\n')
            f.close()
            os.system('chmod +x %s.py' % filename)

    def __configVim(self):
        print '配置vim......................'
        os.system('sh %s %s' % (os.path.join(self.baseScriptRoot, 'config_vim.sh'), os.path.join(self.configureRoot, 'vim')))
        
    def __configIDEA(self):
        print 'idea的配置在%s中，请在软件中导入' % (os.path.join(self.configureRoot, 'idea'))

    def __configTmux(self):
        os.system('cp %s ~/.tmux.conf' % (os.path.join(os.path.join(self.configureRoot, 'tmux'), 'tmux.conf')))
        os.system('echo "alias tmux=\'tmux -2\'" >> ~/.bashrc')
        print '请执行source ~/.bashrc'

    def __execPy(self, name):
        os.system('%s/%s.py' % (self.pyToolRoot, name))
    
    def __timetool(self):
        self.__execPy('timetool')

    def __invalid(self, cmd, argv):
        if len(cmd) == 0:
            return True if len(argv) == 2 else False
        args = [x.strip() for x in cmd.split(' ')]
        ret = len(args)
        if len(argv) - 2 > ret:
            return False
        for i in xrange(1, len(args)+1):
            if args[-i].startswith('[') and args[-i].endswith(']'):
                ret -= 1
            else:
                break
        return True if len(argv) - 2 >= ret else False
    
    def run(self, argv):
        if len(argv) == 1:
            self.__showHelp()
            return
        for cmd in self.cmd_list:
            #print argv[1]
            if self.__invalid(cmd[1], argv) and argv[1] in [x.strip() for x in cmd[0].split(',')]:
                cmd[2](*argv[2:])
                return
        self.__showHelp()


if __name__ == '__main__':
    jungle = Jungle()
    jungle.run(sys.argv)
